# Default values for upload-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: upload-service
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

serviceAccount:
  create: false
