# Generated by Django 4.0.1 on 2022-10-08 20:32

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('upload_type', models.CharField(choices=[('equipment', 'Equipment'), ('summit', 'Summit photo')], default='equipment', max_length=25)),
                ('description', models.TextField(blank=True, null=True)),
                ('surname', models.CharField(blank=True, max_length=1024, null=True)),
                ('firstname', models.CharField(blank=True, max_length=1024, null=True)),
                ('birthyear', models.CharField(blank=True, max_length=1024, null=True)),
                ('address', models.CharField(blank=True, max_length=1024, null=True)),
                ('postcode', models.CharField(blank=True, max_length=1024, null=True)),
                ('town', models.CharField(blank=True, max_length=1024, null=True)),
                ('telephone', models.CharField(blank=True, max_length=1024, null=True)),
                ('email', models.CharField(blank=True, max_length=1024, null=True)),
                ('donate_type', models.CharField(choices=[('museum', 'Swiss Museum'), ('laf_2023', 'LAF 202')], default='museum', max_length=25)),
                ('internal_upload_link', models.CharField(blank=True, max_length=1024, null=True)),
                ('uploaded_image', models.ImageField(null=True, upload_to='images/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
